---
title: "chr_2021_ordination"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
options(scipen = 999)
```

```{r}
chr_data <- read.csv(here("data/2021_us_county_health_counties.csv"))
```


```{r}
median_income <- median(as.numeric(chr_data$median_household_income), na.rm = TRUE)
median_income
```

```{r}
median_primary_care_physicians <- median(as.numeric(chr_data$primary_care_phys_rate), na.rm = TRUE)
median_primary_care_physicians
```


```{r}
median_mental_providers_rate<- median((chr_data$mental_providers_rate), na.rm = TRUE)
median_mental_providers_rate
```

```{r}
median_per_food_insecure<- median(as.numeric(chr_data$per_food_insecure), na.rm = TRUE)
median_per_food_insecure
```


```{r}
median_per_uninsured<- median(as.numeric(chr_data$per_uninsured), na.rm = TRUE)
median_per_uninsured
```



```{r}
median_unemployed<- median(as.numeric(chr_data$per_unemployed), na.rm = TRUE)
median_unemployed
```

```{r}
median_per_single_parent_homes<- median(as.numeric(chr_data$per_child_single_parent_homes), na.rm = TRUE)
median_per_single_parent_homes
```






```{r}
chr_data_disadvantaged<- chr_data %>% 
  select(fips,
         median_household_income,
         primary_care_phys_rate, 
         mental_providers_rate,
         per_food_insecure,
         per_uninsured,
         per_unemployed,
         per_child_single_parent_homes) %>% 
  mutate(low_income = ifelse(median_household_income < median_income, c(1), c(0))) 
 
chr_data_disadvantaged <-  chr_data_disadvantaged %>% 
  mutate(low_primary_care = ifelse(primary_care_phys_rate < median_primary_care_physicians, c(1), c(0))) 
 
chr_data_disadvantaged <-  chr_data_disadvantaged %>% 
  mutate(low_mental_care = ifelse(mental_providers_rate < median_mental_providers_rate, c(1), c(0))) 

chr_data_disadvantaged <-  chr_data_disadvantaged %>%         
  mutate(low_food_security = ifelse(per_food_insecure > median_per_food_insecure, c(1), c(0)))
       

chr_data_disadvantaged <-  chr_data_disadvantaged %>%         
  mutate(high_uninsured = ifelse(per_uninsured > median_per_uninsured, c(1), c(0)))
 

chr_data_disadvantaged <-  chr_data_disadvantaged %>%         
  mutate(high_unemployed = ifelse(per_unemployed > median_unemployed, c(1), c(0)))

chr_data_disadvantaged <-  chr_data_disadvantaged %>%         
  mutate(high_single_parent_homes= ifelse(per_child_single_parent_homes > median_per_single_parent_homes, c(1), c(0)))
 
```



```{r}
chr_data_disadvantaged <- chr_data_disadvantaged %>% 
  filter(low_income == 1 & low_primary_care == 1 & low_mental_care == 1 & low_food_security ==1 & high_uninsured ==1 & high_unemployed ==1 & high_single_parent_homes == 1)
  
```



```{r}
all_disturbance <- read_csv(here("data/all_disturbance_df_county_prep.csv"))

all_ghg <- read_csv(here("data/all_ghg_df_county_prep.csv"))

all_nutrient <- read_csv(here("data/all_nutrient_df_county_prep.csv"))

all_water <- read_csv(here("data/all_water_df_county_prep.csv"))
```



```{r}
all_disturbance <- all_disturbance %>% 
  rename(mean_pressure_disturbance = mean)

all_ghg <- all_ghg %>% 
  rename(mean_pressure_ghg = mean)

all_nutrient <- all_nutrient %>% 
  rename(mean_pressure_nutrient = mean)

all_water <- all_water %>% 
  rename( mean_pressure_water = mean)
```


```{r}
join_1 <- full_join(all_disturbance, all_ghg)

join2 <- full_join(join_1, all_nutrient)

all_pressures <- full_join(join2, all_water)



all_pressures <- all_pressures %>% 
  transform(fips = as.integer(fips))
```

```{r}
all_pressures_disadvantaged <- inner_join(chr_data_disadvantaged, all_pressures)
```

```{r}
sum_disadvantaged_disturbance <- sum(all_pressures_disadvantaged$mean_pressure_disturbance)

sum_disadvantaged_nutrient <- sum(all_pressures_disadvantaged$mean_pressure_nutrient)

sum_disadvantaged_water <- sum(all_pressures_disadvantaged$mean_pressure_water)

sum_disadvantaged_ghg <- sum(all_pressures_disadvantaged$mean_pressure_ghg)


sum_disadvantaged_total_pressures <- sum(sum_disadvantaged_disturbance, sum_disadvantaged_nutrient, sum_disadvantaged_water, sum_disadvantaged_ghg)

sum_disadvantaged_total_pressures

disadvantaged_county_number <- length(chr_data_disadvantaged$fips)

disadvantaged_county_number

total_pressure_per_county_disadvantaged <- sum_disadvantaged_total_pressures/disadvantaged_county_number

total_pressure_per_county_disadvantaged

```

```{r}
median_black <- median(chr_data$per_black)
median_black
```

```{r}
pop_black <- chr_data %>% 
  select(fips, per_black)

pop_black <- pop_black %>% 
  mutate(high_black = ifelse(per_black > median_black, c(1), c(0)))

pop_black <- pop_black %>% 
  filter(high_black == 1)

all_pressures_black <- inner_join(pop_black, all_pressures)


```

```{r}
sum_black_disturbance <- sum(all_pressures_black$mean_pressure_disturbance)

sum_black_nutrient <- sum(all_pressures_black$mean_pressure_nutrient)

sum_black_water <- sum(all_pressures_black$mean_pressure_water)

sum_black_ghg <- sum(all_pressures_black$mean_pressure_ghg)


sum_black_total_pressures <- sum(sum_black_disturbance, sum_black_nutrient, sum_black_water, sum_black_ghg)

sum_black_total_pressures


black_county_number <- length(all_pressures_black$fips)

black_county_number

total_pressure_per_county_black<- sum_black_total_pressures/black_county_number

total_pressure_per_county_black

```

```{r}
pop_low_income <- chr_data %>% 
  select(fips, median_household_income)

pop_low_income <- pop_low_income %>% 
  mutate(low_income = ifelse(median_household_income < median_income, c(1), c(0)))

pop_low_income <- pop_low_income %>% 
  filter(low_income == 1)

all_pressures_low_income <- inner_join(pop_low_income, all_pressures)

```
```{r}
sum_low_income_disturbance <- sum(all_pressures_low_income$mean_pressure_disturbance)

sum_low_income_nutrient <- sum(all_pressures_low_income$mean_pressure_nutrient)

sum_low_income_water <- sum(all_pressures_low_income$mean_pressure_water)

sum_low_income_ghg <- sum(all_pressures_low_income$mean_pressure_ghg)


sum_low_income_total_pressures <- sum(sum_low_income_disturbance, sum_low_income_nutrient, sum_low_income_water, sum_low_income_ghg)

sum_low_income_total_pressures


low_income_county_number <- length(all_pressures_low_income$fips)

low_income_county_number

total_pressure_per_county_low_income<- sum_low_income_total_pressures/low_income_county_number

total_pressure_per_county_low_income

```


```{r}
sum_disturbance <- sum(all_pressures$mean_pressure_disturbance)

sum_nutrient <- sum(all_pressures$mean_pressure_nutrient)

sum_water <- sum(all_pressures$mean_pressure_water)

sum_ghg <- sum(all_pressures$mean_pressure_ghg)

sum_total_pressures <- sum(sum_disturbance, sum_nutrient,
    sum_water, sum_ghg)

sum_total_pressures

county_number = length(all_disturbance$fips)

county_number

total_pressure_per_county_even_distribution <- sum_total_pressures/county_number

total_pressure_per_county_even_distribution
```


```{r}
ghg_normalized <- sum(all_pressures$mean_pressure_ghg)/3224
ghg_normalized

ghg_black <- sum(all_pressures_black$mean_pressure_ghg)/1566
ghg_black

ghg_low_income <- sum(all_pressures_low_income$mean_pressure_ghg)/1566
ghg_low_income

ghg_disadvantaged <- sum(all_pressures_disadvantaged$mean_pressure_ghg)/168
ghg_disadvantaged

nutrient_normalized <- sum(all_pressures$mean_pressure_nutrient)/3224
nutrient_normalized

nutrient_black <- sum(all_pressures_black$mean_pressure_nutrient)/1566
nutrient_black

water_normalized <- sum(all_pressures$mean_pressure_water)/3224
water_normalized

disturbance_normalized <- sum(all_pressures$mean_pressure_disturbance)/3224
disturbance_normalized
```

### Normalization


```{r}
normalize <- function(x) {
return ((x - min(x)) / (max(x) - min(x)))
}
```

```{r}
all_pressures$mean_pressure_disturbance_norm<-normalize(all_pressures$mean_pressure_disturbance)
all_pressures$mean_pressure_ghg_norm<-normalize(all_pressures$mean_pressure_ghg)
all_pressures$mean_pressure_nutrient_norm<-normalize(all_pressures$mean_pressure_nutrient)
all_pressures$mean_pressure_water_norm<-normalize(all_pressures$mean_pressure_water)

normalized_pressures <- all_pressures %>% 
  select(fips,
         mean_pressure_disturbance_norm,
         mean_pressure_ghg_norm,
         mean_pressure_nutrient_norm,
         mean_pressure_water_norm)

normalized_pressures_chr_data <- inner_join(normalized_pressures, chr_data)

normalized_pressures_chr_data <- normalized_pressures_chr_data %>% 
  group_by(fips) %>% 
  mutate(cummulative_pressure = mean_pressure_nutrient_norm +
                                       mean_pressure_ghg_norm +
                                       mean_pressure_disturbance_norm +
                                       mean_pressure_water_norm)

fips_new <- sprintf("%05d", normalized_pressures_chr_data$fips)

normalized_pressures_chr_data <- normalized_pressures_chr_data %>%
  mutate(fips_new = sprintf("%05d", fips)) 

normalized_pressures_chr_data <- subset(normalized_pressures_chr_data, 
                                        select = -fips)

write_csv(normalized_pressures_chr_data, here("data/normalized_pressures_chr_data.csv"))

```

```{r}
sum_disturbance_norm <- sum(normalized_pressures$mean_pressure_disturbance_norm)

sum_nutrient_norm <- sum(normalized_pressures$mean_pressure_nutrient_norm)

sum_water_norm <- sum(normalized_pressures$mean_pressure_water_norm)

sum_ghg_norm <- sum(normalized_pressures$mean_pressure_ghg_norm)

sum_total_pressures_norm <- sum(sum_disturbance_norm, sum_nutrient_norm,
    sum_water_norm, sum_ghg_norm)

sum_total_pressures_norm

county_number = length(normalized_pressures$fips)

county_number

total_pressure_per_county_even_distribution_norm <- sum_total_pressures_norm/county_number

total_pressure_per_county_even_distribution_norm
```

```{r}
low_income_all_pressures_norm <- inner_join(pop_low_income, normalized_pressures)
```

```{r}
sum_low_income_disturbance_norm <- sum(low_income_all_pressures_norm$mean_pressure_disturbance_norm)

sum_low_income_nutrient_norm <- sum(low_income_all_pressures_norm$mean_pressure_nutrient_norm)

sum_low_income_water_norm <- sum(low_income_all_pressures_norm$mean_pressure_water_norm)

sum_low_income_ghg_norm <- sum(low_income_all_pressures_norm$mean_pressure_ghg_norm)


sum_low_income_total_pressures_norm <- sum(sum_low_income_disturbance_norm, sum_low_income_nutrient_norm, sum_low_income_water_norm, sum_low_income_ghg_norm)

sum_low_income_total_pressures_norm


low_income_county_number <- length(low_income_all_pressures_norm$fips)

low_income_county_number

total_pressure_per_county_low_income_norm<- sum_low_income_total_pressures_norm/low_income_county_number

total_pressure_per_county_low_income_norm

```

```{r}
disadvantaged_all_pressures_norm <- inner_join(chr_data_disadvantaged, normalized_pressures)
```

```{r}
sum_disadvantaged_disturbance_norm <- sum(disadvantaged_all_pressures_norm$mean_pressure_disturbance_norm)

sum_disadvantaged_nutrient_norm <- sum(disadvantaged_all_pressures_norm$mean_pressure_nutrient_norm)

sum_disadvantaged_water_norm <- sum(disadvantaged_all_pressures_norm$mean_pressure_water_norm)

sum_disadvantaged_ghg_norm <- sum(disadvantaged_all_pressures_norm$mean_pressure_ghg_norm)


sum_disadvantaged_total_pressures_norm <- sum(sum_disadvantaged_disturbance_norm, sum_disadvantaged_nutrient_norm, sum_disadvantaged_water_norm, sum_disadvantaged_ghg_norm)

sum_disadvantaged_total_pressures_norm


disadvantaged_county_number <- length(disadvantaged_all_pressures_norm$fips)

disadvantaged_county_number

total_pressure_per_county_disadvantaged_norm<- sum_disadvantaged_total_pressures_norm/disadvantaged_county_number

total_pressure_per_county_disadvantaged_norm

```

