---
title: "chr_2021_ordination"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
options(scipen = 999)
```

```{r}
chr_data <- read.csv(here("data/2021_us_county_health_counties.csv"))
```


```{r}
median_income <- median(as.numeric(chr_data$income_ratio), na.rm = TRUE)
median_income
```

```{r}
median_air_pm2.5 <- median(as.numeric(chr_data$air_pollution_avg_daily_pm2.5), na.rm = TRUE)
median_air_pm2.5
```


```{r}
median_drinking_water_violations<- median((chr_data$drinking_water_violation), na.rm = TRUE)
median_drinking_water_violations
```

```{r}
median_per_food_insecure<- median(as.numeric(chr_data$per_food_insecure), na.rm = TRUE)
median_per_food_insecure
```


```{r}
median_per_uninsured<- median(as.numeric(chr_data$per_uninsured), na.rm = TRUE)
median_per_uninsured
```



```{r}
chr_data_disadvantaged<- chr_data %>% 
  select(fips,
         income_ratio,
         air_pollution_avg_daily_pm2.5, 
         drinking_water_violation,
         per_food_insecure,
         per_uninsured) %>% 
  mutate(low_income = ifelse(income_ratio < median_income, c(1), c(0))) 
 
chr_data_disadvantaged <-  chr_data_disadvantaged %>% 
  mutate(low_air_quality = ifelse(air_pollution_avg_daily_pm2.5 > median_air_pm2.5, c(1), c(0))) 
 

chr_data_disadvantaged <-  chr_data_disadvantaged %>%         
  mutate(low_food_security = ifelse(per_food_insecure > median_per_food_insecure, c(1), c(0)))
       

chr_data_disadvantaged <-  chr_data_disadvantaged %>%         
  mutate(high_uninsured = ifelse(per_uninsured > median_per_uninsured, c(1), c(0)))
 
 
```



```{r}
chr_data_disadvantaged <- chr_data_disadvantaged %>% 
  filter(low_income == 1 & low_air_quality == 1 & low_food_security == 1 & high_uninsured ==1)
  
```



```{r}
all_disturbance <- read_csv(here("data/all_disturbance_df_county_prep.csv"))

all_ghg <- read_csv(here("data/all_ghg_df_county_prep.csv"))

all_nutrient <- read_csv(here("data/all_nutrient_df_county_prep.csv"))

all_water <- read_csv(here("data/all_water_df_county_prep.csv"))
```



```{r}
all_disturbance <- all_disturbance %>% 
  rename(mean_pressure_disturbance = mean)

all_ghg <- all_ghg %>% 
  rename(mean_pressure_ghg = mean)

all_nutrient <- all_nutrient %>% 
  rename(mean_pressure_nutrient = mean)

all_water <- all_water %>% 
  rename( mean_pressure_water = mean)
```


```{r}
join_1 <- full_join(all_disturbance, all_ghg)

join2 <- full_join(join_1, all_nutrient)

all_pressures <- full_join(join2, all_water)

all_pressures <- as.numeric(all_pressures$fips)

all_pressures <- all_pressures %>% 
  transform(fips = as.integer(fips))
```

```{r}
all_pressures_disadvantaged <- inner_join(chr_data_disadvantaged, all_pressures)
```

```{r}
sum_disadvantaged_disturbance <- sum(all_pressures_disadvantaged$mean_pressure_disturbance)

sum_disadvantaged_nutrient <- sum(all_pressures_disadvantaged$mean_pressure_nutrient)

sum_disadvantaged_water <- sum(all_pressures_disadvantaged$mean_pressure_water)

sum_disadvantaged_ghg <- sum(all_pressures_disadvantaged$mean_pressure_ghg)


sum_disadvantaged_total_pressures <- sum(sum_disadvantaged_disturbance, sum_disadvantaged_nutrient, sum_disadvantaged_water, sum_disadvantaged_ghg)

sum_disadvantaged_total_pressures

disadvantaged_county_number <- length(chr_data_disadvantaged$fips)

disadvantaged_county_number

total_pressure_per_county_disadvantaged <- sum_disadvantaged_total_pressures/disadvantaged_county_number

total_pressure_per_county_disadvantaged

```

```{r}
sum_disturbance <- sum(all_pressures$mean_pressure_disturbance)

sum_nutrient <- sum(all_pressures$mean_pressure_nutrient)

sum_water <- sum(all_pressures$mean_pressure_water)

sum_ghg <- sum(all_pressures$mean_pressure_ghg)

sum_total_pressures <- sum(sum_disturbance, sum_nutrient,
    sum_water, sum_ghg)

sum_total_pressures

county_number = length(all_disturbance$fips)

county_number

total_pressure_per_county_even_distribution <- sum_total_pressures/county_number

total_pressure_per_county_even_distribution
```

