---
title: "Does being a more rural county mean there is more likely a higher cumulative pressure"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(estimatr)
library(party)
library(randomForest)
options(scipen = 999)

```

```{r}
sum_4_normalized_pressures_health_selective <- read_csv(here("data/sum_4_normalized_pressures_health_selective.csv"))
```


```{r}
# What is the median cumulative pressure per county in the US
median_cumulative_pressure_us <- median(sum_4_normalized_pressures_health_selective$sum_4_cumulative)
median_cumulative_pressure_us
```

```{r}
#What is the median percent rural per county in the US
median_rural <- median(sum_4_normalized_pressures_health_selective$per_rural, na.rm = TRUE)
median_rural
```



```{r}
sum_4_normalized_pressures_health_selective <- sum_4_normalized_pressures_health_selective %>% 
  mutate(sum_4_cumulative_quartile = ntile(sum_4_cumulative, 4),
         per_rural_quartile = ntile(per_rural, 4))
```

```{r}
fourth_quartile_pressure_counties <- sum_4_normalized_pressures_health_selective %>% 
  filter(sum_4_cumulative_quartile == 4)

median(fourth_quartile_pressure_counties$per_rural)
```

```{r}
fourth_quartile_rural_counties <- sum_4_normalized_pressures_health_selective %>% 
  filter(per_rural_quartile == 4)

mean(fourth_quartile_rural_counties$per_rural)

median(fourth_quartile_rural_counties$sum_4_cumulative)

first_quartile_rural_counties <- sum_4_normalized_pressures_health_selective %>% 
  filter(per_rural_quartile == 1)

mean(first_quartile_rural_counties$per_rural)

median(first_quartile_rural_counties$sum_4_cumulative)




```


```{r}
lm_robust(sum_4_cumulative ~ per_rural, data = sum_4_normalized_pressures_health_selective)

ggplot(data = sum_4_normalized_pressures_health_selective, aes(x = per_rural, 
                                                               y = sum_4_cumulative)) +
  geom_smooth(method = "lm")
```


```{r}
lm_robust(sum_4_cumulative ~ per_rural, data = fourth_quartile_pressure_counties)

ggplot(data = fourth_quartile_pressure_counties, aes(x = sum_4_cumulative, 
                                                               y = per_rural)) +
  geom_smooth(method = "lm")
```
```{r}
iowa <- sum_4_normalized_pressures_health_selective %>% 
  filter(state == "Iowa")
```


```{r}
sum_4_normalized_pressures_health_selective_no_na <- sum_4_normalized_pressures_health_selective %>% 
  drop_na(per_rural, median_household_income)


rf1 <- randomForest(formula = sum_4_cumulative ~ per_rural + median_household_income + population, data = sum_4_normalized_pressures_health_selective_no_na, importance = TRUE)

rf1

varImpPlot(rf)
```

```{r}
sum_4_normalized_pressures_health_selective_no_na_health <- sum_4_normalized_pressures_health_selective %>% 
  drop_na(per_rural, median_household_income, per_fair_poor_health, per_access_to_exercise, per_uninsured, primary_care_phys_quartile, mental_health_providers_quartile, per_child_poverty, air_pollution_avg_daily_pm2.5, drinking_water_violation_quartile, per_severe_house_cost_burden, per_severe_housing_problems, per_food_insecure, sum_4_cumulative, per_limited_access_healthy_food, per_black, per_asian, per_am_indian_alaska_native, per_nativeHA_other_pacific_isl, per_hispanic, population
          )

rf_health <- randomForest(per_fair_poor_health ~ per_rural + median_household_income + population + per_access_to_exercise + per_uninsured + primary_care_phys_quartile + mental_health_providers_quartile + per_child_poverty + air_pollution_avg_daily_pm2.5 +  drinking_water_violation_quartile + per_severe_house_cost_burden + per_severe_housing_problems + per_food_insecure + sum_4_cumulative + per_limited_access_healthy_food + per_black + per_asian + per_am_indian_alaska_native + per_nativeHA_other_pacific_isl + per_hispanic,
                          data = sum_4_normalized_pressures_health_selective_no_na_health, importance = TRUE)

print(rf_health)

print(importance(rf_health,type = 2))

varImpPlot(rf_health, type = 2)


```


```{r}
sum_4_normalized_pressures_health_selective_no_na_health <- sum_4_normalized_pressures_health_selective %>% 
  drop_na(per_rural, median_household_income, per_low_birthweight, per_access_to_exercise, per_uninsured, primary_care_phys_quartile, mental_health_providers_quartile, per_child_poverty, air_pollution_avg_daily_pm2.5, drinking_water_violation_quartile, per_severe_house_cost_burden, per_severe_housing_problems, per_food_insecure, sum_4_cumulative, per_limited_access_healthy_food, per_black, per_asian, per_am_indian_alaska_native, per_nativeHA_other_pacific_isl, per_hispanic, population
          )

rf_low_birthweight <- randomForest(per_low_birthweight ~ per_rural + median_household_income + population + per_access_to_exercise + per_uninsured + primary_care_phys_quartile + mental_health_providers_quartile + per_child_poverty + air_pollution_avg_daily_pm2.5 +  drinking_water_violation_quartile + per_severe_house_cost_burden + per_severe_housing_problems + per_food_insecure + sum_4_cumulative + per_limited_access_healthy_food + per_black + per_asian + per_am_indian_alaska_native + per_nativeHA_other_pacific_isl + per_hispanic,
                          data = sum_4_normalized_pressures_health_selective_no_na_health, importance = TRUE)

print(rf_low_birthweight)

print(importance(rf_low_birthweight,type = 2))

varImpPlot(rf_low_birthweight, type = 2)
```


```{r}
sum_4_normalized_pressures_health_selective_no_na_health <- sum_4_normalized_pressures_health_selective %>% 
  drop_na(per_rural, median_household_income, per_low_birthweight, per_access_to_exercise, per_uninsured, primary_care_phys_quartile, mental_health_providers_quartile, per_child_poverty, air_pollution_avg_daily_pm2.5, drinking_water_violation_quartile, per_severe_house_cost_burden, per_severe_housing_problems, per_food_insecure, sum_4_cumulative, per_limited_access_healthy_food, per_black, per_asian, per_am_indian_alaska_native, per_nativeHA_other_pacific_isl, per_hispanic, population
          )

rf_low_birthweight <- randomForest(per_fair_poor_health ~ per_rural + median_household_income + population + per_access_to_exercise + per_uninsured + primary_care_phys_quartile + mental_health_providers_quartile + per_child_poverty + air_pollution_avg_daily_pm2.5 +  drinking_water_violation_quartile + per_severe_house_cost_burden + per_severe_housing_problems + per_food_insecure + sum_4_cumulative + per_limited_access_healthy_food + per_black + per_asian + per_am_indian_alaska_native + per_nativeHA_other_pacific_isl + per_hispanic,
                          data = sum_4_normalized_pressures_health_selective_no_na_health, importance = TRUE)

print(rf_low_birthweight)

print(importance(rf_low_birthweight,type = 2))

varImpPlot(rf_low_birthweight, type = 2)
```


```{r}
sum_4_normalized_pressures_health_selective_no_na_health <- sum_4_normalized_pressures_health_selective %>% 
  drop_na(per_rural, median_household_income, life_expectancy, per_access_to_exercise, per_uninsured, primary_care_phys_quartile, mental_health_providers_quartile, per_child_poverty, air_pollution_avg_daily_pm2.5, drinking_water_violation_quartile, per_severe_house_cost_burden, per_severe_housing_problems, per_food_insecure, sum_4_cumulative, per_limited_access_healthy_food, per_black, per_asian, per_am_indian_alaska_native, per_nativeHA_other_pacific_isl, per_hispanic, population
          )

rf_life_expectancy <- randomForest(life_expectancy ~ per_rural + median_household_income + population + per_access_to_exercise + per_uninsured + primary_care_phys_quartile + mental_health_providers_quartile + per_child_poverty + air_pollution_avg_daily_pm2.5 +  drinking_water_violation_quartile + per_severe_house_cost_burden + per_severe_housing_problems + per_food_insecure + sum_4_cumulative + per_limited_access_healthy_food + per_black + per_asian + per_am_indian_alaska_native + per_nativeHA_other_pacific_isl + per_hispanic,
                          data = sum_4_normalized_pressures_health_selective_no_na_health, importance = TRUE)

print(rf_life_expectancy)

print(importance(rf_life_expectancy,type = 2))

varImpPlot(rf_life_expectancy, type = 2)
```





```{r}
sum_4_normalized_pressures_health_selective_no_na_health <- sum_4_normalized_pressures_health_selective %>% 
  drop_na(per_rural, median_household_income, per_freq_mental_distress, per_access_to_exercise, per_uninsured, primary_care_phys_quartile, mental_health_providers_quartile, per_child_poverty, air_pollution_avg_daily_pm2.5, drinking_water_violation_quartile, per_severe_house_cost_burden, per_severe_housing_problems, per_food_insecure, sum_4_cumulative, per_limited_access_healthy_food, per_black, per_asian, per_am_indian_alaska_native, per_nativeHA_other_pacific_isl, per_hispanic, population
          )

rf_per_frequent_mental_distress <- randomForest(per_freq_mental_distress ~ per_rural + median_household_income + population + per_access_to_exercise + per_uninsured + primary_care_phys_quartile + mental_health_providers_quartile + per_child_poverty + air_pollution_avg_daily_pm2.5 +  drinking_water_violation_quartile + per_severe_house_cost_burden + per_severe_housing_problems + per_food_insecure + sum_4_cumulative + per_limited_access_healthy_food + per_black + per_asian + per_am_indian_alaska_native + per_nativeHA_other_pacific_isl + per_hispanic,
                          data = sum_4_normalized_pressures_health_selective_no_na_health, importance = TRUE)

print(rf_per_frequent_mental_distress)

print(importance(rf_per_frequent_mental_distress,type = 2))

varImpPlot(rf_per_frequent_mental_distress, type = 2)
```




```{r}
sum_4_normalized_pressures_health_selective_no_na_health <- sum_4_normalized_pressures_health_selective %>% 
  drop_na(per_rural, median_household_income, per_freq_physical_distress, per_access_to_exercise, per_uninsured, primary_care_phys_quartile, mental_health_providers_quartile, per_child_poverty, air_pollution_avg_daily_pm2.5, drinking_water_violation_quartile, per_severe_house_cost_burden, per_severe_housing_problems, per_food_insecure, sum_4_cumulative, per_limited_access_healthy_food, per_black, per_asian, per_am_indian_alaska_native, per_nativeHA_other_pacific_isl, per_hispanic, population
          )

rf_per_frequent_physical_distress <- randomForest(per_freq_physical_distress ~ per_rural + median_household_income + population + per_access_to_exercise + per_uninsured + primary_care_phys_quartile + mental_health_providers_quartile + per_child_poverty + air_pollution_avg_daily_pm2.5 +  drinking_water_violation_quartile + per_severe_house_cost_burden + per_severe_housing_problems + per_food_insecure + sum_4_cumulative + per_limited_access_healthy_food + per_black + per_asian + per_am_indian_alaska_native + per_nativeHA_other_pacific_isl + per_hispanic,
                          data = sum_4_normalized_pressures_health_selective_no_na_health, importance = TRUE)

print(rf_per_frequent_physical_distress)

print(importance(rf_per_frequent_physical_distress,type = 2))

varImpPlot(rf_per_frequent_physical_distress, type = 2)
```





```{r}
first_quartile_pressure_counties <- sum_4_normalized_pressures_health_selective %>% 
  filter(sum_4_cumulative_quartile == 1)
```

```{r}
fourth_n_first <- full_join(first_quartile_pressure_counties, fourth_quartile_pressure_counties)

fourth_n_first <- fourth_n_first %>%  
   mutate(high_pressure = ifelse(sum_4_cumulative_quartile == 4, c("yes"), c("no")))



```


```{r}
as.factor(fourth_n_first$high_pressure)

fourth_n_first <- fourth_n_first %>% 
  mutate(high_pressure_factor = as.factor(high_pressure)) %>% 
  drop_na(per_rural, median_household_income, residential_segregation_nonwhite_white) 



rf <- randomForest(high_pressure_factor ~ per_rural + median_household_income + population,     
                 data = fourth_n_first)

print(rf)

print(importance(rf,type = 2))

varImpPlot(rf)
```




```{r}

```

```{r}
test_forest <- randomForest(sum_4_cumulative ~ sum_1_ghg + sum_1_water +  sum_1_disturbance + sum_1_nutrient, data = sum_4_normalized_pressures_health_selective)

print(test_forest)

importance(test_forest, type = 2)


```


```{r}

```

