---
title: "sum to 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999)
```

```{r}
# Load in environmental pressures of food production data

all_disturbance <- read_csv(here("data/all_disturbance_df_county_prep.csv"))

all_ghg <- read_csv(here("data/all_ghg_df_county_prep.csv"))

all_nutrient <- read_csv(here("data/all_nutrient_df_county_prep.csv"))

all_water <- read_csv(here("data/all_water_df_county_prep.csv"))
```

```{r}
# Rename from "mean' to mean_pressure_"pressure"

all_disturbance <- all_disturbance %>% 
  rename(mean_pressure_disturbance = mean)

all_ghg <- all_ghg %>% 
  rename(mean_pressure_ghg = mean)

all_nutrient <- all_nutrient %>% 
  rename(mean_pressure_nutrient = mean)

all_water <- all_water %>% 
  rename( mean_pressure_water = mean)
```



```{r}
# Join environmental pressures of food production data

disturbance_ghg_join <- full_join(all_disturbance, all_ghg)

disturbance_ghg_nutrient_join <- full_join(disturbance_ghg_join, all_nutrient)

disturbance_ghg_nutrient_water_join <- full_join(disturbance_ghg_nutrient_join, all_water)

all_pressures <- disturbance_ghg_nutrient_water_join %>% 
  transform(fips = as.integer(fips))
```

```{r}
# Load in county health rankings data

chr_data <- read.csv(here("data/2021_us_county_health_counties.csv"))
```

```{r}
# Join county health rankings data with environmental pressures of food production data 

chr_data_pressures <- inner_join(chr_data, all_pressures)

chr_data_pressures <- chr_data_pressures %>%
  mutate(fips = sprintf("%05d", fips)) 
```



```{r}
# Normalized pressures summed to 1, cummulative pressure is summed to 4

sum_to_1_pressures <- chr_data_pressures %>% 
  mutate(sum_1_disturbance = mean_pressure_disturbance/sum(mean_pressure_disturbance),
         sum_1_nutrient = mean_pressure_nutrient/sum(mean_pressure_nutrient),
         sum_1_ghg = mean_pressure_ghg/sum(mean_pressure_ghg),
         sum_1_water = mean_pressure_water/sum(mean_pressure_water),
         sum_4_cumulative = (sum_1_disturbance + sum_1_nutrient +
                               sum_1_ghg + sum_1_water))
```

```{r}
regions <- read_csv(here("data/us_state_regions.csv"))

regions <- regions %>% 
  rename(state = State)
```


```{r}
sum_1_pressures_regions <- full_join(sum_to_1_pressures, regions)
```




```{r}
sum_4_normalized_pressures_health_selective <- sum_1_pressures_regions %>% 
  select(fips,
         state,
         Region,
         Division,
         county,
         sum_1_disturbance,
         sum_1_water,
         sum_1_ghg,
         sum_1_nutrient,
         sum_4_cumulative,
         years_potential_life_lost_rate,
         years_potential_life_lost_rate_quartile,
         per_fair_poor_health,
         per_fair_poor_health_quartile,
         avg_num_physically_unhealthy_days,
         avg_num_physically_unhealthy_days_quartile,
         avg_num_mentally_unhealthy_days,
         avg_num_mentally_unhealthy_days_quartile,
         per_low_birthweight,
         per_low_birthweight_quartile,
         per_adult_obesity,
         per_adult_obesity_quartile,
         per_access_to_exercise,
         per_access_to_exercise_quartile,
         per_uninsured,
         per_uninsured_quartile,
         primary_care_phys_quartile, # high = less care per person
         mental_health_providers_quartile,
         per_unemployed,
         per_unemployed_quartile,
         per_child_poverty,
         per_child_poverty_quartile,
         per_child_single_parent_homes,
         per_child_single_parent_homes_quartile,
         air_pollution_avg_daily_pm2.5,
         air_pollution_avg_daily_pm2.5_quartile,
         drinking_water_violation_quartile, #1 = no, 4 = yes
         per_severe_housing_problems,
         per_severe_house_cost_burden,
         life_expectancy,
         child_mortality_rate,
         per_freq_mental_distress,
         per_freq_physical_distress,
         per_adults_diabetes,
         per_food_insecure,
         per_limited_access_healthy_food,
         per_uninsured_adults,
         median_household_income,
         per_homeowners,
         population,
         per_black,
         per_nativeHA_other_pacific_isl,
         per_am_indian_alaska_native,
         per_asian,
         per_hispanic,
         per_non_hispanic_white,
         residential_segregation_black_white,
         residential_segregation_nonwhite_white,
         per_rural,
         per_smokers,
         per_physically_inactive, 
         per_excessive_drinking,
         per_flu_vaccinated,
         per_completed_hs, 
         per_some_college,
         traffic_volume,
         per_broadband_access
         )

write_csv(sum_4_normalized_pressures_health_selective, here("data/sum_4_normalized_pressures_health_selective.csv"))
```

